{
    "name": "Equipment Management",
    "version": "18.0.1.0.0",
    "summary": "Manage equipment, assign it to employees and keep the history",
    "category": "Human Resources",
    "license": "LGPL-3",
    "depends": ["base", "hr"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/equipment_category_views.xml",
        "views/equipment_views.xml",
        "views/equipment_assignment_views.xml",
        "views/hr_employee_views.xml",
        "data/equipment_sequence.xml",
        "views/menus.xml",
    ],
    "demo": ["demo/demo.xml"],
    "application": True,
    "installable": True,
}
